function fit_params = extract_fit_params_from_fit(fit)

fit_params = [fit.center_point_x,...
                fit.center_point_y,...
                fit.center_sd_x,...
                fit.center_sd_y,...
                fit.center_rotation_angle  ,...             
                fit.color_weight_a,...
                fit.color_weight_b,...
                fit.color_weight_c,...
                fit.x_dim,...
                fit.y_dim,...
                fit.num_colors,...
                fit.fit_surround,...
                fit.surround_sd_scale,...
                fit.surround_amp_scale,...
                fit.scale_one,...
                fit.scale_two,...
                fit.tau_one,...
                fit.tau_two,...
                fit.n_one_filters,...
                fit.frame_number,...
                fit.n_two_filters];